server:
  port: 9010
  
spring:
  application:
    name: "student"
  datasource:
    url: jdbc:mysql://localhost:3306/studentdb
    username: root
    password: Abhishek@123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always